### ISSUE TITLE
bessel / spherical bessel integrals

### ISSUE THREAD

**Issue by xzackli** [JuliaApproximation/OscillatoryIntegrals.jl#6]
I'd like to make a feature request for integrals of a fun multiplied by a Bessel / spherical Bessel function. The prediction of some common cosmological observables requires the evaluation of ~10^6 spherical Bessel integrals, basically a grid of Bessel orders nu and frequencies k for `j_nu(kx)`. I'm motivated to see how a Chebyshev-based method matches up in the work-precision plane with [OscillatoryIntegralsODE.jl](https://github.com/xzackli/OscillatoryIntegralsODE.jl) or the oscillatory extension to the DE method in [DoubleExponentialFormulas.jl](https://github.com/machakann/DoubleExponentialFormulas.jl). 

I thought I could try to make this contribution, but I am thoroughly mystified / impressed by what seems like the full algorithm of Keller, packed into line 25-26,

```julia
 \([BasisFunctional(ceil(Integer,ω),space(f));
    Derivative(space(f))+im*ω*I], Any[0.,f]; tolerance=10maximum(f.coefficients)*eps())
```
I find this line very challenging to parse, despite ostensibly knowing the general strategy of Keller. This is the ApproxFun way of solving a system of two equations. The BasisFunctional seems to be a structure from ApproxFunBase that packs a space with a number? Why is the frequency `ceil` to an int? Why label the array Any in `Any[0.,f]`, aren't all function arrays of type Any[]? I'm having a hard time connecting this example to those in the docs.

Sorry for bothering you, and thank you for making so many useful packages for numerical analysis.

**Comment by xzackli** [comment]
Sorry again for bothering you about this. After ruminating on my problem, I think it makes sense for me to achieve collocation via Chebyshev by carefully implementing Keller07 myself, directly manipulating the coefficients from FastTransforms. My use case has the integral inside two nested loops, so the payoff of reusing the Chebyshev points, ensuring type stability, doing only the partial pivoted Gaussian elimination based on tolerance, etc. seems worth it.

**Comment by dlfivefifty** [comment]
My take on Keller's method for Fourier integrals is that it is Levin's method with the "boundary" condition that the `ceil(ω)`-th Chebyshev coefficient is zero. Using what I'd call the ultraspsherical spectral method (see my paper with @ajt60gaibb) to get a sparse discretisation for the ODE. 

**Warning** this code doesn't have the best feature of Keller's method that if `ω` is large you can forgo the boundary condition completely. So yes you are better off implementing it your self (But DON'T CALL IT COLLOCATION!! If you are doing collocation you are doing it wrong.)

So to answer your query: `BasisFunctional(ceil(Integer,ω),space(f))` just means the row vector `[0 …  0 1 0 …]`, that is `ceil(Integer,ω)-1` zeros, a `1`, and then infinite zeros. Then `Derivative(space(f))+im*ω*I` is of course the Levin differnetial operator `u' + im*ω*u`. 

> label the array `Any` in `Any[0.,f]`

That was probably just a work around for a bug. Since `f` is a `Fun` then, no, its not true that all function arrays are type `Any`, it would by default convert `0` to a `Fun`.

> Why is the frequency ceil to an int?

Because we need to impose a specific coefficient to be zero. Coefficients are integer-valued.

**Comment by xzackli** [comment]
Thank you, this is very helpful!
